# Push sรณ aciona quando uma determinada branch for acionada, nesse caso, somente quando a branche development receber um push

name: WorkFlow - Push branch
run-name: Running - ${{ github.event_name }}
on:
  push:
    branches:
      - development
jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comentario
        run: |
          echo "Workflow Push"
        